name: Bug Report
description: Create a report to help reproduce and correct the bug.

body:
- type: textarea
  attributes:
    label: Describe the bug
    description: >
      A concise description of the bug.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Observed Results
    description: |
      Please paste or describe the results you observe. If you observe an error, please paste the error message including the **full traceback** of the exception.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Code to Reproduce
    description: |
      Please add a code example that can reproduce the error when running it. Be as succinct as possible, **do not depend on external data files**: instead you can use [sklearn.datasets.make_regression](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_regression.html), [sklearn.datasets.make_classification](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_classification.html) or generate synthetic data using `numpy.random`.

      Crafting a code example requires some effort on your side but it really helps to quickly reproduce the problem and analyze its cause without any ambiguity. Ambiguous bug reports tend to be slower to fix because they will require more effort and discussions to pin-point the precise conditions necessary to reproduce the problem.
    placeholder: |
      ```
      Sample code to reproduce the problem
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Results
    description: >
      Please paste or describe the expected results.
    placeholder: >
      Example: No error is thrown.
  validations:
    required: true
- type: textarea
  attributes:
    label: Version
    render: shell
    description: |
      Please run the following and paste the output below.
      ```python
      import lce; lce.__version__
      ```
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
