name: lce workflow

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: test python lce
    defaults:
      run:
        working-directory: ./lce
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: install dependencies
        run: |
          pip install -r ../requirements.txt
          pip install pytest pytest-cov
      - name: run tests and collect coverage
        run: pytest --cov=./ --cov-report=xml
      - name: upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@master
